In [2]:
import numpy as np
A=np.array([[56.0,0.0,4.4,68.0],
          [1.2,104,52,8],
          [1.8,135,99,0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [12]:
cal=A.sum(axis=1)
cal

array([128.4, 165.2, 236.7])

In [9]:
print(A/cal.reshape(1,4))

[[0.94915254 0.         0.02831403 0.88426528]
 [0.02033898 0.43514644 0.33462033 0.10403121]
 [0.03050847 0.56485356 0.63706564 0.01170351]]


In [10]:
print(A/cal)

[[0.94915254 0.         0.02831403 0.88426528]
 [0.02033898 0.43514644 0.33462033 0.10403121]
 [0.03050847 0.56485356 0.63706564 0.01170351]]


In [11]:
percent=100*A/cal
percent

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

In [24]:
x=("Parth","Shah")
firstname,lastname=x
print(firstname,lastname,x)

Parth Shah ('Parth', 'Shah')


In [21]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b
c

array([[ 0.07878988,  0.06571929,  0.7366102 ],
       [-1.12631469, -0.81272634, -3.10528117]])